apiVersion: v1
kind: Namespace
metadata:
  name: simple-http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-http
  namespace: simple-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-http
  template:
    metadata:
      labels:
        app: simple-http
    spec:
      containers:
        - name: simple-http
          image: ghcr.io/vojtechmares/demo-apps/simple-http:latest
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: simple-http
  namespace: simple-http
spec:
  selector:
    app: simple-http
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-http
  namespace: simple-http
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: nginx
  rules:
    - host: simple-http.maresdemo.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: simple-http
                port:
                  name: http
  tls:
    - hosts:
        - simple-http.maresdemo.com
      secretName: simple-http-ingress-tls
