apiVersion: v1
kind: Namespace
metadata:
  name: log-print
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-print
  namespace: log-print
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-print
  template:
    metadata:
      labels:
        app: log-print
    spec:
      automountServiceAccountToken: false
      containers:
        - name: log-print
          image: ghcr.io/vojtechmares/demo-apps/log-print:latest
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "32Mi"
              cpu: "10m"
